package dataStructures;

public enum FormatProblem {
	INVALIDCOMPARTMENT,
	INVALIDAXIS,
	INVALIDSTATESTRICT,
	INVALIDSTATE,
	EXPECTEDNUMBER,
	INVALIDGENENAME,
	INVALIDCELL,
	INVALIDGENE,
	INVALIDCELLNAME
}
